// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using NetTopologySuite.Geometries;
using Microsoft.EntityFrameworkCore;


namespace OstaFandy.DAL.Entities;

public partial class Address
{
    [Key]
    public int Id { get; set; }

    public int UserId { get; set; }

    [Required]
    [Column("Address")]
    [StringLength(255)]
    public string Address1 { get; set; }

    [Required]
    [StringLength(100)]
    public string City { get; set; }

    [Column(TypeName = "decimal(9, 6)")]
    public decimal Latitude { get; set; }

    [Column(TypeName = "decimal(9, 6)")]
    public decimal Longitude { get; set; }

   public Point Location { get; set; }


    [Required]
    [StringLength(20)]
    public string AddressType { get; set; }

    public bool IsDefault { get; set; }

    public bool IsActive { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    [InverseProperty("Address")]
    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();

    [InverseProperty("DefaultAddress")]
    public virtual ICollection<Client> Clients { get; set; } = new List<Client>();

    [InverseProperty("DefaultAddress")]
    public virtual ICollection<Handyman> Handymen { get; set; } = new List<Handyman>();

    [ForeignKey("UserId")]
    [InverseProperty("Addresses")]
    public virtual User User { get; set; }
}