// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OstaFandy.DAL.Entities;

public partial class BookingService
{
    [Key]
    public int Id { get; set; }

    public int BookingId { get; set; }

    public int ServiceId { get; set; }

    [ForeignKey("BookingId")]
    [InverseProperty("BookingServices")]
    public virtual Booking Booking { get; set; }

    [ForeignKey("ServiceId")]
    [InverseProperty("BookingServices")]
    public virtual Service Service { get; set; }
}