// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OstaFandy.DAL.Entities;

public partial class Chat
{
    [Key]
    public int Id { get; set; }

    public int BookingId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime StartedAt { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? EndedAt { get; set; }

    [ForeignKey("BookingId")]
    [InverseProperty("Chats")]
    public virtual Booking Booking { get; set; }

    [InverseProperty("Chat")]
    public virtual ICollection<Message> Messages { get; set; } = new List<Message>();
}