// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OstaFandy.DAL.Entities;

public partial class Client
{
    [Key]
    public int UserId { get; set; }

    public int? DefaultAddressId { get; set; }

    [InverseProperty("Client")]
    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();

    [ForeignKey("DefaultAddressId")]
    [InverseProperty("Clients")]
    public virtual Address DefaultAddress { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("Client")]
    public virtual User User { get; set; }
}