// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OstaFandy.DAL.Entities;

public partial class Handyman
{
    [Key]
    public int UserId { get; set; }

    public int SpecializationId { get; set; }

    [Column(TypeName = "decimal(9, 6)")]
    public decimal? Latitude { get; set; }

    [Column(TypeName = "decimal(9, 6)")]
    public decimal? Longitude { get; set; }

    public int? DefaultAddressId { get; set; }

    [Required]
    [StringLength(20)]
    public string NationalId { get; set; }

    [Required]
    [StringLength(255)]
    public string NationalIdImg { get; set; }

    [Required]
    [StringLength(255)]
    public string Img { get; set; }

    public int ExperienceYears { get; set; }

    [Required]
    [StringLength(20)]
    public string Status { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime UpdatedAt { get; set; }

    [InverseProperty("User")]
    public virtual ICollection<BlockDate> BlockDates { get; set; } = new List<BlockDate>();

    [ForeignKey("DefaultAddressId")]
    [InverseProperty("Handymen")]
    public virtual Address DefaultAddress { get; set; }

    [InverseProperty("Handyman")]
    public virtual ICollection<JobAssignment> JobAssignments { get; set; } = new List<JobAssignment>();

    [ForeignKey("SpecializationId")]
    [InverseProperty("Handymen")]
    public virtual Category Specialization { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("Handyman")]
    public virtual User User { get; set; }
}