// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OstaFandy.DAL.Entities;

[Index("BookingId", Name = "UQ_BookingId", IsUnique = true)]
public partial class JobAssignment
{
    [Key]
    public int Id { get; set; }

    public int BookingId { get; set; }

    public int HandymanId { get; set; }

    [Required]
    [StringLength(20)]
    public string Status { get; set; }

    public bool IsActive { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime AssignedAt { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CompletedAt { get; set; }

    [ForeignKey("BookingId")]
    [InverseProperty("JobAssignment")]
    public virtual Booking Booking { get; set; }

    [ForeignKey("HandymanId")]
    [InverseProperty("JobAssignments")]
    public virtual Handyman Handyman { get; set; }

    [InverseProperty("JobAssignment")]
    public virtual ICollection<Quote> Quotes { get; set; } = new List<Quote>();
}