// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OstaFandy.DAL.Entities;

public partial class Message
{
    [Key]
    public int Id { get; set; }

    public int ChatId { get; set; }

    public int SenderId { get; set; }

    [Required]
    [StringLength(1000)]
    public string Content { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? SentAt { get; set; }

    public bool? IsRead { get; set; }

    [ForeignKey("ChatId")]
    [InverseProperty("Messages")]
    public virtual Chat Chat { get; set; }

    [ForeignKey("SenderId")]
    [InverseProperty("Messages")]
    public virtual User Sender { get; set; }
}