// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OstaFandy.DAL.Entities;

public partial class Quote
{
    [Key]
    public int Id { get; set; }

    public int JobAssignmentId { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal Price { get; set; }

    public int? EstimatedMinutes { get; set; }

    [Required]
    [StringLength(500)]
    public string Notes { get; set; }

    [Required]
    [StringLength(20)]
    public string Status { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    [ForeignKey("JobAssignmentId")]
    [InverseProperty("Quotes")]
    public virtual JobAssignment JobAssignment { get; set; }
}