// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OstaFandy.DAL.Entities;

[Index("Name", "CategoryId", Name = "UQ_Services_Name_Category", IsUnique = true)]
public partial class Service
{
    [Key]
    public int Id { get; set; }

    public int CategoryId { get; set; }

    [Required]
    [StringLength(100)]
    public string Name { get; set; }

    [Required]
    [StringLength(255)]
    public string Description { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal FixedPrice { get; set; }

    public int EstimatedMinutes { get; set; }

    [Required]
    [StringLength(20)]
    public string ServiceType { get; set; }

    public bool IsActive { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime UpdatedAt { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    [InverseProperty("Service")]
    public virtual ICollection<BookingService> BookingServices { get; set; } = new List<BookingService>();

    [ForeignKey("CategoryId")]
    [InverseProperty("Services")]
    public virtual Category Category { get; set; }
}